import type { Metadata } from "next";
import { Electrolize, Barrio } from "next/font/google";
import "./globals.scss";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const electrolizeSans = Electrolize({
  weight:["400"],
  variable: "--font-electrolize-sans",
  subsets: ["latin"],
});

const barrio = Barrio({
  weight:["400"],
  variable: "--font-barrio-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${electrolizeSans.variable} ${barrio.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
