'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import {useState} from 'react';
import Header from "@/components/Header";
import SearchBar from "@/components/SearchBar";
import DisplayRecipe from "@/components/Displayrecipe"
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 const [inputValue,setInputValue] = useState<string>("")

     const handleSubmit = (e) => {
        e.preventDefault()
        console.log(inputValue)
    }

  return (
    <html lang="en">
      <body>
        <Header />
        <SearchBar input={setInputValue} submit={()=>handleSubmit()} inputValue={inputValue}/>
        {children}
      </body>
    </html>
  );
}
